DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS readers;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS publisher;
DROP TABLE IF EXISTS document;
DROP TABLE IF EXISTS copy;
DROP TABLE IF EXISTS branch;
DROP TABLE IF EXISTS book;

CREATE TABLE admins(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username VARCHAR(20) NOT NULL,
	password VARCHAR(10) NOT NULL
);

CREATE TABLE readers(
	RID INTEGER PRIMARY KEY AUTOINCREMENT,
	RNAME VARCHAR(20) NOT NULL,
	RADDRESS VARCHAR(20),
	PHONE_NO INT(10) NOT NULL
);

CREATE TABLE reservation(
	RES_NO INTEGER PRIMARY KEY,
	DTIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE book(
	BOOKID INTEGER PRIMARY KEY AUTOINCREMENT,
	ISBN INTEGER(6) UNIQUE
);

CREATE TABLE document(
	DOCID INTEGER PRIMARY KEY AUTOINCREMENT,
	TITLE VARCHAR(20) NOT NULL,
	PDATE VARCHAR(20) NOT NULL,
	PUBID INTEGER,
	FOREIGN KEY(PUBID) REFERENCES publisher(PUBLISHERID)
);

CREATE TABLE publisher(
	PUBLISHERID INTEGER PRIMARY KEY AUTOINCREMENT,
	PUBNAME VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(20) NOT NULL
);

CREATE TABLE copy(
	DOCID INTEGER,
	COPYNO INTEGER PRIMARY KEY AUTOINCREMENT,
	POSITION VARCHAR(20) NOT NULL,
	FOREIGN KEY(DOCID) REFERENCES document(DOCID)
);

CREATE TABLE branch(
	BID INTEGER PRIMARY KEY AUTOINCREMENT,
	LNAME VARCHAR(20) NOT NULL,
	LOCATION VARCHAR(20) NOT NULL
);

